# Generated by Django 4.2.1 on 2023-05-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='editorial',
            new_name='editorials',
        ),
    ]
